name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version

      - name: Install dependencies
        run: |
          forge install foundry-rs/forge-std@v1.9.2 --no-commit
          forge install OpenZeppelin/openzeppelin-contracts@v5.0.2 --no-commit
          forge install OpenZeppelin/openzeppelin-contracts-upgradeable@v5.0.2 --no-commit
          forge install Cyfrin/foundry-devops@0.2.2 --no-commit

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
